### ISSUE TITLE
Error while running the example code `MultiPoint Sequential`

### ISSUE THREAD

**Issue by shikhar-saxena** [mikediessner/nubo#1]
I'm running the example code given in the documentation [https://nubopy.com/_build/html/multipoint_sequential.html](https://nubopy.com/_build/html/multipoint_sequential.html).

Code (for reference):
```py
import torch
from nubo.acquisition import MCExpectedImprovement, MCUpperConfidenceBound
from nubo.models import GaussianProcess, fit_gp
from nubo.optimisation import multi_sequential
from nubo.test_functions import Hartmann6D
from nubo.utils import gen_inputs
from gpytorch.likelihoods import GaussianLikelihood


# test function
func = Hartmann6D(minimise=False)
dims = 6

# specify bounds
bounds = torch.tensor([[0., 0., 0., 0., 0., 0.], [1., 1., 1., 1., 1., 1.]])

# training data
x_train = gen_inputs(num_points=dims*5,
                     num_dims=dims,
                     bounds=bounds)
y_train = func(x_train)

# Bayesian optimisation loop
iters = 10

for iter in range(iters):

    # specify Gaussian process
    likelihood = GaussianLikelihood()
    gp = GaussianProcess(x_train, y_train, likelihood=likelihood)

    # fit Gaussian process
    fit_gp(x_train, y_train, gp=gp, likelihood=likelihood, lr=0.1, steps=200)

    # specify acquisition function
    # acq = MCExpectedImprovement(gp=gp, y_best=torch.max(y_train), samples=512)
    acq = MCUpperConfidenceBound(gp=gp, beta=1.96**2, samples=512)

    # optimise acquisition function
    x_new, _ = multi_sequential(func=acq, method="Adam", batch_size=4, bounds=bounds, lr=0.1, steps=200, num_starts=5)

    # evaluate new point
    y_new = func(x_new)

    # add to data
    x_train = torch.vstack((x_train, x_new))
    y_train = torch.hstack((y_train, y_new))

    # print new best
    if torch.max(y_new) > torch.max(y_train[:-y_new.size(0)]):
        best_eval = torch.argmax(y_train)
        print(f"New best at evaluation {best_eval+1}: \t Inputs: {x_train[best_eval, :].numpy().reshape(dims).round(4)}, \t Outputs: {-y_train[best_eval].numpy().round(4)}")

# results
best_iter = int(torch.argmax(y_train))
print(f"Evaluation: {best_iter+1} \t Solution: {-float(y_train[best_iter]):.4f}")
```

I received the following error:
```
Traceback (most recent call last):
  File "bla.py", line 2, in <module>
    from nubo.acquisition import MCExpectedImprovement, MCUpperConfidenceBound
  File "/home2/underzated/py-envs/bo-env/lib/python3.8/site-packages/nubo/__init__.py", line 1, in <module>
    from . import (
  File "/home2/underzated/py-envs/bo-env/lib/python3.8/site-packages/nubo/acquisition/__init__.py", line 1, in <module>
    from .analytical import UpperConfidenceBound, ExpectedImprovement
  File "/home2/underzated/py-envs/bo-env/lib/python3.8/site-packages/nubo/acquisition/analytical.py", line 5, in <module>
    from .acquisition_function import AcquisitionFunction
  File "/home2/underzated/py-envs/bo-env/lib/python3.8/site-packages/nubo/acquisition/acquisition_function.py", line 6, in <module>
    class AcquisitionFunction:
  File "/home2/underzated/py-envs/bo-env/lib/python3.8/site-packages/nubo/acquisition/acquisition_function.py", line 14, in AcquisitionFunction
    def __call__(self, x: Tensor | ndarray) -> Tensor | ndarray:
TypeError: unsupported operand type(s) for |: 'torch._C._TensorMeta' and 'type'
```
It failed on python version `3.8.3`. I was able to run it with python version `3.11.3` though. So I think it's some python version issue.

**Comment by mikediessner** [comment]
Hi Shikar,

thanks for reaching out. You are right it is an issue with the Python version. We are using the shorthand `|` for `Union` as recommended [here](https://docs.python.org/3/library/typing.html#typing.Union). This was introduced in Python 3.10 and it will throw an error for any version before this. I have updated the requirements accordingly. Thanks for bringing this to our attention. Cheers!
